//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STLTapReport.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class beerList
    {
        public int name_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double abv { get; set; }
        public string style_id { get; set; }
    }
}
