//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STLTapReport.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class beer
    {
        public beer()
        {
            this.users = new HashSet<user>();
        }
    
        public int beerID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double abv { get; set; }
        public int styleID { get; set; }
    
        public virtual style style { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
