//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STLTapReport.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.beers = new HashSet<beer>();
            this.styles = new HashSet<style>();
        }
    
        public int userID { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public bool isAdmin { get; set; }
        public string favStyle { get; set; }
    
        public virtual ICollection<beer> beers { get; set; }
        public virtual ICollection<style> styles { get; set; }
    }
}
